USE mspl;

CREATE TABLE IF NOT EXISTS wp_policy_sale (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    policy_id BIGINT UNSIGNED NOT NULL,
    policy_number VARCHAR(64),
    region VARCHAR(191),
    premium DECIMAL(10,2),
    days INT,
    departure DATE,
    `return` DATE,
    insured_names VARCHAR(191),
    insured_dob DATE,
    passport_number VARCHAR(64),
    national_id VARCHAR(64),
    insured_phone VARCHAR(32),
    insured_email VARCHAR(191),
    insured_address VARCHAR(191),
    country_of_origin VARCHAR(191),
    agent_id BIGINT UNSIGNED,
    agency_id BIGINT UNSIGNED DEFAULT NULL,
    agent_name VARCHAR(191),
    amount_paid DECIMAL(10,2),
    service_fee_amount DECIMAL(10,2) DEFAULT 0.00,
    maljani_commission_amount DECIMAL(10,2) DEFAULT 0.00,
    agent_commission_amount DECIMAL(10,2) DEFAULT 0.00,
    agent_commission_status ENUM('unpaid','paid','received','disputed') DEFAULT 'unpaid',
    agency_comm_disputed_note TEXT,
    net_to_insurer DECIMAL(10,2) DEFAULT 0.00,
    insurer_payment_status ENUM('not_due','due','paid','failed') DEFAULT 'not_due',
    insurer_payment_reference VARCHAR(191),
    insurer_payment_date DATETIME NULL,
    insurer_payment_note TEXT,
    payment_reference VARCHAR(191),
    payment_status ENUM('confirmed','failed','pending','paid','unconfirmed') DEFAULT 'pending',
    policy_status ENUM('approved','unconfirmed','confirmed','active','claimed','expired','archived','pending_review','cancelled') DEFAULT 'unconfirmed',
    workflow_status ENUM('draft','pending_review','submitted_to_insurer','approved','active') DEFAULT 'draft',
    terms LONGTEXT,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
) CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS wp_maljani_agencies (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    name VARCHAR(191) NOT NULL,
    contact_name VARCHAR(191),
    contact_email VARCHAR(191),
    contact_phone VARCHAR(32),
    commission_rate DECIMAL(5,2) DEFAULT 0.00,
    commission_percent DECIMAL(5,2) DEFAULT 0.00,
    user_id BIGINT UNSIGNED DEFAULT 0,
    notes TEXT,
    agency_name VARCHAR(191),
    ira_licence_number VARCHAR(100),
    insurer_agreement_ids LONGTEXT,
    status ENUM('pending', 'approved', 'rejected') DEFAULT 'pending',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
) CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
